spring:
    application:
        name: gateway
server:
    port: 8072
eureka:
    instance:
        prefer-ip-address: true
client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true
endpoint:
    gateway:
        enabled: true
    health:
        probes:
            enabled: true

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


