server:
  port: 8072
spring:
  application:
    name: gateway
  cloud:
    gateway:
     discovery:
       locator:
        enabled: true
        lowercase-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-size: 10
#        permitted-number-of-calls-in-half-open-state: 2
#        automatic-transition-from-open-to-half-open-enabled: true
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 10s
#        wait-duration-in-half-open-state: 5s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true